"""
Classifies NSE/BSE tickers into Large / Mid / Small cap using
Nifty index membership (updated May 2025, rebalanced quarterly).
"""

# Nifty 50 constituents
NIFTY_50 = {
    "ADANIENT","ADANIPORTS","APOLLOHOSP","ASIANPAINT","AXISBANK",
    "BAJAJ-AUTO","BAJAJFINSV","BAJFINANCE","BHARTIARTL","BEL",
    "BPCL","BRITANNIA","CIPLA","COALINDIA","DIVISLAB","DRREDDY",
    "EICHERMOT","GRASIM","HCLTECH","HDFCBANK","HDFCLIFE","HEROMOTOCO",
    "HINDALCO","HINDUNILVR","ICICIBANK","INDUSINDBK","INFY","ITC",
    "JSWSTEEL","KOTAKBANK","LT","M&M","MARUTI","NESTLEIND","NTPC",
    "ONGC","POWERGRID","RELIANCE","SBILIFE","SBIN","SUNPHARMA",
    "TATACONSUM","TATAMOTORS","TATASTEEL","TCS","TECHM","TITAN",
    "TRENT","ULTRACEMCO","WIPRO",
}

# Nifty Next 50 (rounds out top 100 = Large Cap)
NIFTY_NEXT_50 = {
    "ABB","ACC","AMBUJACEM","AUBANK","AUROPHARMA","BAJAJHLDNG",
    "BANKBARODA","BERGEPAINT","BOSCHLTD","CANBK","CHOLAFIN","COLPAL",
    "DABUR","DMART","FEDERALBNK","GAIL","GODREJCP","HAVELLS",
    "ICICIPRULI","ICICIGI","INDUSTOWER","INDHOTEL","LUPIN","MARICO",
    "MUTHOOTFIN","NAUKRI","NMDC","OFSS","PAGEIND","PETRONET","PFC",
    "PIDILITIND","PNB","RECLTD","SHREECEM","SIEMENS","TORNTPHARM",
    "TATAPOWER","TVSMOTOR","UPL","VEDL","VOLTAS","ZOMATO","ASHOKLEY",
    "BALKRISHNA","DELHIVERY","JINDALSTEL","MPHASIS","PIIND","SOLARINDS",
}

# Nifty Midcap 150 sample (major constituents — not exhaustive)
NIFTY_MIDCAP_150 = {
    "ABBOTINDIA","AIAENG","APARINDS","APOLLOTYRE","ASTRAL","ATUL",
    "AVANTIFEED","BATAINDIA","BAYERCROP","CARBORUNIV","CDSL","CEATLTD",
    "CONCOR","COROMANDEL","CROMPTON","CUMMINSIND","DEEPAKNTR","ELGIEQUIP",
    "ENGINERSIN","ESCORTS","EXIDEIND","FINEORG","FLUOROCHEM","GALAXY",
    "GLAND","GLAXO","GNFC","GODREJIND","GRINDWELL","GSPL","HAPPSTMNDS",
    "HATSUN","HAWKINCOOK","HFCL","HINDCOPPER","HONAUT","HUDCO","IGPL",
    "IPCALAB","JBCHEPHARM","JKCEMENT","JKTYRE","JSWENERGY","KAJARIACER",
    "KANSAINER","KARURVYSYA","KPIGREEN","KPITTECH","LAURUSLABS","LINDEINDIA",
    "LALPATHLAB","LTTS","MFSL","METROPOLIS","MPHASIS","NAVINFLUOR","NBCC",
    "NUVOCO","NYKAA","OBEROIRLTY","OFSS","OLECTRA","PGHH","PHOENIXLTD",
    "POLYCAB","POONAWALLA","PTCIL","RADICO","RAIN","RAMCOCEM","RKFORGE",
    "ROUTE","SAFARI","SANOFI","SCHAEFFLER","SKFINDIA","SOBHA","SONACOMS",
    "SUNDARMFIN","SUNDRMFAST","SUPREMEIND","SYNGENE","TASTYBITE","TEJASNET",
    "THERMAX","TIMKEN","TIMETECHNO","TITAGARH","TRITURBINE","UCOBANK",
    "UNIONBANK","VAIBHAVGBL","VIJAYA","VMART","VSTIND","WELCORP","WHIRLPOOL",
    "WOCKPHARMA","ZYDUSLIFE","ZYDUSWELL",
}

LARGE_CAP = NIFTY_50 | NIFTY_NEXT_50


def classify_equity_cap(ticker: str) -> str:
    """Return 'Large Cap', 'Mid Cap', or 'Small Cap' for an NSE/BSE ticker."""
    sym = ticker.upper().replace("-EQ", "").replace("-BE", "").replace("-BL", "")
    if sym in LARGE_CAP:
        return "Large Cap"
    if sym in NIFTY_MIDCAP_150:
        return "Mid Cap"
    return "Small Cap"
